version: '3.8'
services:
  lb:
    image: nginx-plus-centos-7:r23
    ports:
    - "80:80"
    - "8000:8080"
    - "8001:8081"
    volumes:
    - type: "bind"
      source: "./configs/nginx/conf.d"
      target: "/etc/nginx/conf.d"
    - type: "bind"
      source: "./configs/nginx/stream.d"
      target: "/etc/nginx/stream.d"
    - type: "bind"
      source: "./configs/nginx/nginx.conf"
      target: "/etc/nginx/nginx.conf"
  hello:
    image: nginxdemos/nginx-hello